# Generated by Django 5.2 on 2025-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='graduation_year',
        ),
        migrations.AddField(
            model_name='education',
            name='duration',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
